# Generated by Django 6.0.5 on 2026-05-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='lng',
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='shop.city', verbose_name='Город'),
        ),
    ]
