# Generated by Django 6.0.5 on 2026-05-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_city_remove_pickuppoint_lat_remove_pickuppoint_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
    ]
